### ISSUE TITLE
pip install doesn't complete

### ISSUE THREAD

**Issue by justinlent** [sigopt/sigopt-python#24]
I'm working in an anaconda environment and getting this error when trying to pip install sigopt. Any ideas on how to workaround?  After some googling not sure if this 'requests' package installed via distutils way back when is an artifact of Anaconda or simply Mac OS

```
Collecting sigopt-python
  Using cached sigopt_python-1.0.0-py2-none-any.whl
Collecting requests==2.5.1 (from sigopt-python)
  Using cached requests-2.5.1-py2.py3-none-any.whl
Collecting simplejson>=3.5.2 (from sigopt-python)
Installing collected packages: requests, simplejson, sigopt-python
  Found existing installation: requests 2.8.1
Detected a distutils installed project ('requests') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
```

**Comment by pfhayes** [comment]
I've seen this error before - typically it can be fixed by uninstalling the offending package (`requests`) manually.

You can find where `requests` is installed by

    >> import requests
    >> print requests.__file__

Then go to that directory (on OS X, it is probably /usr/lib/python2.7) and delete any `requests.py`, `requests.pyc`, and `requests.XXX.egg-info` files.

Let me know if that helps!

**Comment by justinlent** [comment]
Thanks! That worked.
