### ISSUE TITLE
Dealing with dead/zombie/detached runs

### ISSUE THREAD

**Issue by plstcharles** [sigopt/sigopt-python#321]
Hello all!

I was wondering if there are any guidelines/tips regarding the best way to handle zombie runs from either the CLI or python API. Ideally, I'd love to notify an experiment that a particular run failed due to an outside-hyperparameter reason which has no consequence on future runs. Specifically, I want to differentiate two types of failed runs:
 - If a run dies because a set of hyperparameters was invalid and it caused a configuration error, we should report it as such and avoid that hyperparameter configuration in the future. I assume this is done via the [`sigopt.log_failure()`](https://app.sigopt.com/docs/api_reference/python_tracking#log_failure) function, as I did not notice the same hyperparameter combination being tried again in future runs.
 - If a run dies because its resources were preempted or because its host died unexpectedly, it might not have sent a proper termination signal at all, meaning SigOpt might still consider the run as active (so, a zombie). The experiment configuration tied to this run might need to be re-evaluated in the future (since it might be good!), so the run should not be considered "failed" like in the first case.

Is there a way to flag the latter type of failed runs as "dead" without "failures"? Is there an easy way to do this via CLI or via the Python API directly?

Thanks!

**Comment by tjs-intel** [comment]
@plstcharles you are correct that `sigopt.log_failure()` is intended to mark runs as failed to the optimizer so that the same hyperparameter configuration is not offered again.

To achieve the desired result of marking runs as failed while not influencing the optimizer, the only feature that could help you there is to delete/archive the run (these are identical operations in our API). This can be done at the bottom of the training run page, where you should find an "Archive Run" button. To delete training runs with this python library you will need to use the deprecated Connection object.
```
connection = sigopt.Connection("YOUR_API_TOKEN")
connection.training_runs(training_run_id).delete()
```

Hope this helps!

**Comment by plstcharles** [comment]
Ahhh yes indeed, this is exactly what I was looking for. I'll be using this for sure --- at least, via the Python API, as doing it manually seems impractical for big experiments that are not tightly monitored.

Is there a public reason why the Connection object is being deprecated? I hope this kind of functionality will be kept in the future, as using sigopt to manage experiments using preemptable machines (e.g. AWS spot instances) is a fairly common use case.

Thanks!

**Comment by tjs-intel** [comment]
@plstcharles I wasn't sure if we implemented this functionality after our client redesign, but it turns out that it is available today!

```
sigopt.archive_run(training_run_id)
```
